### ISSUE TITLE
can the container run under user permission

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#136]
i see the container and it files runs under `999` for the db one and `msmp` runs under `root` is there a way to make it run under my user?

**Comment by Nostradamus1973** [comment]
Good morning,

So, this is unable to have these variables?:
```
environment:
      - PGID=1000
      - PUID=1000
```

**Comment by aniel300** [comment]
i have it like that but it doesn't make a difference

**Comment by Nostradamus1973** [comment]
> i have it like that but it doesn't make a difference

Bummer, this script looks sexy-as-hell, I really wanna use it, but, without that it's a deal breaker for me.

I currently use HLS-Proxy, it has the ability to do Stream Pools, but, I'd much rather use this script instead because it has a singular purpose and is lightweight unlike hls-proxy.
I thought the creator of this project would prioritize this instead it's been switched to low priority. I bet there's a ton of Emby/Jellyfin users that would love this script.

@sonroyaalmerol Any chance you could fast track that feature and I'll spread the good word for you.

Thx and have a great day.

**Comment by aniel300** [comment]
well the dev is not wrong. things works as it is, this request of mine is just a convenience thing more than anything so...

**Comment by Nostradamus1973** [comment]
> well the dev is not wrong. things works as it is, this request of mine is just a convenience thing more than anything so...

I hear ya, I'm sure he has life stuff to deal with like the rest of us, but, I try staying away from running things as root, I'm sure he'll get to it whenever the priority stuff gets taken care of.
I'm watching all the activity of this Git, so, when that get's implemented I'll get the word out in the Emby and Jellyfin forums.

**Comment by Nostradamus1973** [comment]
@aniel I had a question that maybe you could answer.
I just want to make sure I have my facts correct. With this script, can I add multiple m3u's that are Identical? And load balance off them?
Also, my m3u's from IPTVeditor are tiny links and don't have the *.m3u connotation. Will that work?
Thx

**Comment by aniel300** [comment]
yes, yes (although i haven't use the load balancing/gallback feature yet). as for the iptveditor part, u can either use the non "xxx.m3u" url or "xxx.m3u" from iptveditor.

**Comment by aniel300** [comment]
join the discord so we don't bloat this posts.
