### ISSUE TITLE
Ability to Exclude Groups

### ISSUE THREAD

**Issue by raf02** [sonroyaalmerol/m3u-stream-merger-proxy#155]
It would be great to have the ability to exclude groups. The idea being that new groups from the source playlist would be added by default, but unwanted groups could still be filtered out.

One approach would be to add an EXCLUDE_GROUPS variables. Any groups that match the variables would be excluded from the merged playlist. Essentially a "blacklisting" approach to managing groups. The INCLUDE_GROUPS variables would still take precedence if set.

**Comment by sonroyaalmerol** [comment]
You may test out #156 and see if it works for you. The test image should be built with the URL posted by a bot in the same PR. I'll merge it later within this weekend after I check for any performance drops due to the additional filters.

| ENV VAR                     | Description                                              | Default Value | Possible Values                                |
|-----------------------------|----------------------------------------------------------|---------------|------------------------------------------------|
| INCLUDE_GROUPS_1, INCLUDE_GROUPS_2, INCLUDE_GROUPS_X    | Set channels to include based on groups (Takes precedence over EXCLUDE_GROUPS_X) | N/A | Go regexp |
| EXCLUDE_GROUPS_1, EXCLUDE_GROUPS_2, EXCLUDE_GROUPS_X    | Set channels to exclude based on groups | N/A | Go regexp |
| INCLUDE_TITLE_1, INCLUDE_TITLE_2, INCLUDE_TITLE_X    | Set channels to include based on title (Takes precedence over EXCLUDE_TITLE_X) | N/A | Go regexp |
| EXCLUDE_TITLE_1, EXCLUDE_TITLE_2, EXCLUDE_TITLE_X    | Set channels to exclude based on title | N/A | Go regexp |

**Comment by sonroyaalmerol** [comment]
Merged to the main branch. This feature will be included in the next release.
