### ISSUE TITLE
Replace Redis with SQLite

### ISSUE THREAD

**Issue by dotbanana** [sonroyaalmerol/m3u-stream-merger-proxy#184]
I want to pitch the idea here to replace Redis with SQLite.  
Contrary to popular belief SQLite, even when used from disk, is faster than Redis from memory, because it is not going through the network stack. 

![image](https://github.com/user-attachments/assets/b3e94914-0903-4dd6-be38-4aabeb978161)
Src: https://wafris.org/blog/rearchitecting-for-sqlite

As redis points out themselves:  
> Redis is a server: all commands involve network or IPC round trips. It is meaningless to compare it to embedded data stores such as SQLite, Berkeley DB, Tokyo/Kyoto Cabinet, etc ... because the cost of most operations is primarily in network/protocol management.
https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/benchmarks/#pitfalls-and-misconceptions   
  
I think this would make this application smaller, less complex and more easy to troubleshoot/fix, which is always a good thing in my opinion.

**Comment by sonroyaalmerol** [comment]
I don't disagree with any of your points and I am very much aware of the performance overhead with Redis. The project started with SQLite as well.

However, I realized that SQL databases in general did not fit the use-case of this app. The need for database migration scripts whenever a new M3U attribute is added in the parsing functionality was cumbersome. Actually, this app should not need any persistent database in the first place.

Redis is only required right now because I literally just replaced SQLite with it for faster development at that time, not for performance. I didn't have the time to change parts of the code that depended on an external database as there were too many bug fixes with higher priority at that time. Redis was easy to implement and did not need any fixed structure.

The plan is to completely remove any external dependency as a requirement (including Redis) for this exact reason:

> make this application smaller, less complex and more easy to troubleshoot/fix, which is always a good thing in my opinion.

I'll move it up the priority list since it seems mostly stable at its current state.

**Comment by sonroyaalmerol** [comment]
`0.16.0` has completely removed the Redis dependency. I might still decide to add a database as an option (not a requirement) in future versions but this should be sufficient for now.
