### ISSUE TITLE
new db url structure has changed with https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/191

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#193]
it seems db url structure has change with https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/191. i have been likening this persistent db url structure that u created as part of https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/154#issuecomment-2354262501. i haven't fully checked if it breaks the separation of live, movie and series but url generation looks different.

here is an example:
current db url structure for live: `https://xxx/proxy/aniel3000/aniel3000iscool/au-espn-play-25-d`
new db url structure for live: `https://xxx/p/BRASNIC-DRAZEN/RqKAVKvJRu/KLUv_QQAyQMAeyJ0aXRsZSI6IjAgS2FuYWwiLCJ0dmdfaWQiOiJvLWthbmFsIiwidHZnX2NoIjoiIiwibG9nbyI6Imh0dHA6Ly9yZXBvLm90dHNob3cubmV0L3Bpa29uaS9ib3NuYS8wa2FuYWwuZ2lmIiwiZ3JvdXAiOiJCaUgife4ced4
`

**Comment by sonroyaalmerol** [comment]
This is not a bug and is due to the `0.16.0` release. Please read the `README` and the release descriptions regarding the changes in the scheme. `0.15.2` is the last version to have the old scheme. Feel free to use that version if it breaks your workflow. Unless there are any problems regarding playback or grouping, I won't consider it as a bug.

**Comment by aniel300** [comment]
new schema works for me, not sure why I made this post, thank u.
