### ISSUE TITLE
After update container doesnt run

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#77]
Since the update, it seems the container no longer runs at all.

For context, I create the container using a script that handles docker create commands.

I created a redis container, allocated it an IP address, and appears to be up and running as expected.

However, now when I launch the m3u merger container, it gets stuck in a reboot loop.

Unfortunately the error logs are not very helpful at all, this is the only entries I see when I check the container logs:

exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory

As a side note, could redis not be included as part of the m3u stream merger image rather than a separate container and needing a separate IP address?

**Comment by aniel300** [comment]
am getting the same error. tried with latest and dev and same issue

**Comment by blackwhitebear8** [comment]
same error

**Comment by sonroyaalmerol** [comment]
Sorry about that. For some reason using scratch as base image does not work as expected anymore since the latest release. I've released a temporary hotfix `0.11.2` with the side effect of the image size being larger (from ~3mb to ~100mb compressed). I have no time to investigate deeper right now but will do once i find the time.

Including Redis as part of the image will probably never happen. Typically, a docker image should only do one thing. Adding Redis to the base image would require me to add supervisor or another dependency to manage both daemons running inside the container. This is why you never see docker images for apps with databases like mysql/postgresql embedded in them. Also, being able to update Redis separately would be impossible if it's included in the image.

Generally, if you're only using docker-compose, you wouldn't need to allocate any IP address manually or even expose any ports as long as they're in the same docker-compose file (or same docker network). The name used for the container is also the hostname of the container itself. In the example docker-compose from the README, `REDIS_ADDR=redis:6379` works just fine without any changes if the name of the redis container is also `redis`.
